LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional

LOCAL_MODULE := Substratum

LOCAL_CERTIFICATE := PRESIGNED

LOCAL_SRC_FILES := Substratum.apk

LOCAL_MODULE_CLASS := APPS

LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)

LOCAL_MODULE_PATH := $(TARGET_OUT_DATA)

LOCAL_DEX_PREOPT := false

include $(BUILD_PREBUILT)
